RACE_NAME_MAP = {
    "bahrain": "Bahrain",
    "saudi": "Saudi Arabia",
    "australia": "Australia",
    "japan": "Japan",
    "china": "China",
    "miami": "Miami",
    "emilia": "Emilia Romagna",
    "monaco": "Monaco",
    "canada": "Canada",
    "spain": "Spain",
    "austria": "Austria",
    "silverstone": "Great Britain",
    "hungary": "Hungary",
    "belgium": "Belgium",
    "netherlands": "Netherlands",
    "monza": "Italy",
    "baku": "Azerbaijan",
    "singapore": "Singapore",
    "austin": "United States",
    "mexico": "Mexico City",
    "saopaulo": "São Paulo",
    "lasvegas": "Las Vegas",
    "qatar": "Qatar",
    "abudhabi": "Abu Dhabi",
}

TEAM_ID_MAP = {
    "Red Bull": "red_bull",
    "Red Bull Racing": "red_bull",
    "Mercedes": "mercedes",
    "Ferrari": "ferrari",
    "McLaren": "mclaren",
    "Aston Martin": "aston_martin",
    "Alpine": "alpine",
    "Williams": "williams",
    "AlphaTauri": "rb",
    "RB": "rb",
    "Haas F1 Team": "haas",
    "Haas": "haas",
    "Sauber": "sauber",
    "Kick Sauber": "sauber",
    "Alfa Romeo": "sauber",
}

DRIVER_CODE_MAP = {
    "max_verstappen": "VER",
    "sergio_perez": "PER",
    "lewis_hamilton": "HAM",
    "george_russell": "RUS",
    "charles_leclerc": "LEC",
    "carlos_sainz": "SAI",
    "lando_norris": "NOR",
    "oscar_piastri": "PIA",
    "fernando_alonso": "ALO",
    "lance_stroll": "STR",
    "pierre_gasly": "GAS",
    "esteban_ocon": "OCO",
    "alexander_albon": "ALB",
    "logan_sargeant": "SAR",
    "yuki_tsunoda": "TSU",
    "daniel_ricciardo": "RIC",
    "kevin_magnussen": "MAG",
    "nico_hulkenberg": "HUL",
    "valtteri_bottas": "BOT",
    "guanyu_zhou": "ZHO",
}
